version: '3.8'

services:
  app:
    image: ponwick/portafolio:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
    command: sh -c "php artisan storage:link && php artisan serve --host=0.0.0.0 --port=80"
