version: '3.8'

services:
  php:
    image: ponwick/portafolio:php-fpm
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
