apiVersion: apps/v1
kind: Deployment
metadata:
  name: portafolio
  namespace: portafolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portafolio
  template:
    metadata:
      labels:
        app: portafolio
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-copy
          image: ponwick/portafolio:php-fpm-0.0.1
          command: ["sh", "-c", "cp -a /var/www/. /var/www/html"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
      containers:
        - name: php
          image: ponwick/portafolio:php-fpm-0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_URL
              value: "https://k8s-ponsianodeloor.dev/portafolio"
            - name: ASSET_URL
              value: "https://k8s-ponsianodeloor.dev/portafolio"
          envFrom:
            - secretRef:
                name: portafolio-secrets
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: app-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: portafolio-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: portafolio
  namespace: portafolio
spec:
  type: NodePort
  selector:
    app: portafolio
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32002
