apiVersion: v1
kind: ConfigMap
metadata:
  name: portafolio-nginx-conf
  namespace: portafolio
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        root /var/www/html/public;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Serve files stored in storage/app/public
        location /storage {
            alias /var/www/html/storage/app/public;
            try_files $uri $uri/ /index.php?$query_string;
            access_log off;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
            fastcgi_index index.php;
        }
    }
